# Generated by Django 4.2.3 on 2023-07-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Set Title')),
                ('sub_title', models.CharField(max_length=50, verbose_name='Set Sub Title')),
                ('description', models.TextField(verbose_name='Set Description')),
                ('img', models.ImageField(upload_to='media/%Y-%m-%d', verbose_name='Upload Background Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published ?')),
                ('url', models.URLField(verbose_name='Set Video Url')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Main',
                'ordering': ['id'],
            },
        ),
    ]
