# Generated by Django 4.2.3 on 2023-07-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/%Y-%m-%d', verbose_name='Upload Slider Image')),
                ('date', models.DateField(verbose_name='Set Date')),
                ('title', models.CharField(max_length=50, verbose_name='Set Title')),
                ('location', models.CharField(max_length=50, verbose_name='Set Location')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published ?')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Upcoming Events Slider',
                'verbose_name_plural': 'Upcoming Events Slider',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'ordering': ['id'], 'verbose_name': 'Main', 'verbose_name_plural': 'Main'},
        ),
    ]
