# Generated by Django 4.2.3 on 2023-07-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_upcomingevents_alter_main_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSpad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/%Y-%m-%d', verbose_name='Upload Image')),
                ('title', models.CharField(max_length=50, verbose_name='Set Title')),
                ('description', models.TextField(verbose_name='Set Description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published ?')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'About Spad',
                'verbose_name_plural': 'About Spad',
            },
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Main', 'verbose_name_plural': 'Main'},
        ),
        migrations.AlterField(
            model_name='main',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='main',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
    ]
