# Generated by Django 4.2.3 on 2023-07-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutspad_alter_main_options_alter_main_time_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/%Y-%m-%d', verbose_name='Upload Image')),
                ('title', models.CharField(max_length=50, verbose_name='Set Title')),
                ('description', models.TextField(verbose_name='Set Description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published ?')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
