# Generated by Django 4.2.3 on 2023-07-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Set Track Title')),
                ('track', models.FileField(upload_to='files/%Y-%m-%d', verbose_name='Upload Audio')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published ?')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
