# Generated by Django 4.2.3 on 2023-07-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ticketsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsection',
            name='time',
        ),
    ]
