# Generated by Django 4.2.3 on 2023-07-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_ticketsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Set Title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Set Subtitle')),
                ('img', models.ImageField(upload_to='media/%Y-%m-%d', verbose_name='Upload Background Image')),
                ('days_left', models.IntegerField(blank=True, verbose_name='Set Days')),
                ('hours_left', models.IntegerField(blank=True, verbose_name='Set Hours')),
                ('minutes_left', models.IntegerField(blank=True, verbose_name='Set Minutes')),
                ('seconds_left', models.IntegerField(blank=True, verbose_name='Set Seconds')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published ?')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Ticket Section',
                'verbose_name_plural': 'Ticket Section',
            },
        ),
    ]
