# Generated by Django 4.2.3 on 2023-07-29 15:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_ticketsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Set Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Set Email')),
                ('address', models.CharField(max_length=50, verbose_name='Set Address')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Set Facebook Url')),
                ('twitter_url', models.CharField(blank=True, max_length=50, verbose_name='Set Twitter Url')),
                ('instagram_url', models.CharField(blank=True, help_text='If You Have Any More Social Accounts And Want To Add Your Webpage , Please Contact With Page Creator Company.', max_length=50, verbose_name='Set Instagram Url')),
            ],
        ),
    ]
