# Generated by Django 4.2.3 on 2023-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_staticinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Subscriber Email')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletter',
            },
        ),
        migrations.AlterModelOptions(
            name='staticinfo',
            options={'verbose_name': 'Page Information', 'verbose_name_plural': 'Page Information'},
        ),
    ]
