# Generated by Django 4.2.3 on 2023-07-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_imagegroup_slills'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegroup',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/%Y-%m-%d'),
        ),
    ]
