# Generated by Django 4.2.3 on 2023-07-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_imagegroup_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegroup',
            old_name='img',
            new_name='i',
        ),
    ]
