# Generated by Django 4.2.3 on 2023-07-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_img_imagegroup_i'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slills',
            new_name='Skills',
        ),
        migrations.RenameField(
            model_name='imagegroup',
            old_name='i',
            new_name='img_first',
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='img_fiveth',
            field=models.ImageField(blank=True, upload_to='media/%Y-%m-%d'),
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='img_fourth',
            field=models.ImageField(blank=True, upload_to='media/%Y-%m-%d'),
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='img_second',
            field=models.ImageField(blank=True, upload_to='media/%Y-%m-%d'),
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='img_seventh',
            field=models.ImageField(blank=True, upload_to='media/%Y-%m-%d'),
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='img_sixth',
            field=models.ImageField(blank=True, upload_to='media/%Y-%m-%d'),
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='img_third',
            field=models.ImageField(blank=True, upload_to='media/%Y-%m-%d'),
        ),
    ]
