# Generated by Django 4.2.3 on 2023-07-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_aboutfeed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutFeed',
        ),
    ]
