# Generated by Django 4.2.3 on 2023-07-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_aboutfeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='sub_title',
        ),
    ]
