# Generated by Django 4.2.3 on 2023-07-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_skills_sub_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
