# Generated by Django 4.2.3 on 2023-08-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Set Price')),
                ('img', models.ImageField(upload_to='media/%Y-%m-%d', verbose_name='Upload Image')),
                ('title', models.CharField(max_length=50, verbose_name='Set Title')),
                ('app_store', models.URLField(verbose_name='Set App Store URL')),
                ('google_play', models.URLField(verbose_name='Set Google Play URL')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published ?')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Discography',
                'verbose_name_plural': 'Discography',
                'ordering': ['id'],
            },
        ),
    ]
