# Generated by Django 4.2.3 on 2023-08-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_discography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Set Title')),
                ('set_time', models.TimeField(verbose_name='Set Time')),
                ('set_date', models.DateField(verbose_name='Set Date')),
                ('location', models.CharField(max_length=50, verbose_name='Set Location')),
                ('price', models.FloatField(verbose_name='Set Price')),
                ('img', models.ImageField(upload_to='media/%Y-%m-%d', verbose_name='Upload Image')),
                ('description', models.TextField(verbose_name='Set Description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published ?')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Tours',
                'verbose_name_plural': 'Tours',
            },
        ),
    ]
