# Generated by Django 4.2.3 on 2023-08-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_tours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.IntegerField(verbose_name='Set Price'),
        ),
    ]
