# Generated by Django 4.2.3 on 2023-08-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetailView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Set Title')),
                ('sub_title', models.CharField(max_length=50, verbose_name='Set Sub Title')),
                ('description', models.TextField(verbose_name='Set Description')),
                ('set_date', models.DateField(verbose_name='Set Date')),
                ('type', models.CharField(blank=True, choices=[('music', 'Music'), ('festival', 'Festival'), ('tinternational', 'Tinternational'), ('event', 'Event')], max_length=255)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published ?')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Blog Detail View',
                'verbose_name_plural': 'Blog Detail Views',
            },
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['id'], 'verbose_name': 'Videos', 'verbose_name_plural': 'Videos'},
        ),
    ]
