# Generated by Django 4.2.3 on 2023-08-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_blogdetailview_alter_videos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('music', 'Music'), ('festival', 'Festival'), ('tinternational', 'Tinternational'), ('event', 'Event')], max_length=255)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published ?')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='BlogDetailView',
        ),
    ]
