# Generated by Django 4.2.3 on 2023-08-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_blogdetailview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailview',
            name='connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_id', to='main.blog', verbose_name='Select Type'),
        ),
    ]
