# Generated by Django 4.2.3 on 2023-08-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_blogdetailview_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailview',
            name='img',
            field=models.ImageField(null=True, upload_to='media/%Y-%m-%d', verbose_name='Upload Image'),
        ),
    ]
