# Generated by Django 4.2.3 on 2023-08-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_blogdetailview_blogdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdetail',
            options={'ordering': ['id'], 'verbose_name': 'Blog Detail View', 'verbose_name_plural': 'Blog Detail Views'},
        ),
    ]
