# Generated by Django 4.2.3 on 2023-08-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_blogdetail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='quote',
            field=models.TextField(null=True, verbose_name='Set Quote'),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='quote_author',
            field=models.CharField(max_length=50, null=True, verbose_name='Quote Author'),
        ),
    ]
