# Generated by Django 4.2.3 on 2023-08-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_contact_alter_blogdetail_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
        ),
    ]
