# Generated by Django 4.2.3 on 2023-08-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='comment',
            new_name='message',
        ),
    ]
