# Generated by Django 4.2.3 on 2023-08-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_rename_comment_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfeed',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='aboutspad',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='quote',
            field=models.TextField(blank=True, help_text="It's Not Important To Write Quote", null=True, verbose_name='Set Quote'),
        ),
        migrations.AlterField(
            model_name='discography',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='imagegroup',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='main',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='services',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='instagram_url',
            field=models.CharField(blank=True, help_text='If You Have Any More Social Accounts And Want To Add Your Webpage, Please Contact With Page Creator Company.', max_length=50, verbose_name='Set Instagram Url'),
        ),
        migrations.AlterField(
            model_name='ticketsection',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
        migrations.AlterField(
            model_name='youtubefeed',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published?'),
        ),
    ]
