# Generated by Django 4.2.3 on 2023-08-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_aboutfeed_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Установить заголовок')),
                ('description', models.TextField(verbose_name='Установить текст')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published?')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
    ]
