# Generated by Django 4.2.3 on 2023-08-05 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_staticinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_details', to='main.blog', verbose_name='Select Type'),
        ),
    ]
