# Generated by Django 4.2.3 on 2023-08-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_blogdetail_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
