# Generated by Django 4.2.3 on 2023-08-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_blogdetail_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.RemoveField(
            model_name='blogdetail',
            name='slug',
        ),
    ]
